# Badge: Lint: validate
name: "Lint: validate"

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  validate:
    name: tofu validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: opentofu/setup-opentofu@9d84900f3238fab8cd84ce47d658d25dd008be2f # v1.0.8
      - name: Cache providers
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: .terraform/providers
          key: ${{ runner.os }}-tofu-${{ hashFiles('.terraform.lock.hcl') }}
      - run: tofu init -backend=false
      - run: tofu validate -no-color
